"""
Emit Manim Community Edition scene source that stages a static chart PNG.
"""

from __future__ import annotations

import textwrap

from .models import DataVizBridgeRequest


def emit_scene_script(request: DataVizBridgeRequest, chart_filename: str) -> str:
    """
    Build a `.py` file body that references `chart_filename` in the working directory.

    LaTeX snippets in `tex_explanations` are wrapped in MathTex; keep them short.
    """
    cls = request.manim.scene_class_name
    tex_block = ""
    for i, frag in enumerate(request.manim.tex_explanations):
        # Inside generated `MathTex(r"...")`, preserve single backslashes for LaTeX.
        safe_tex = frag.replace('"', '\\"')
        tex_block += f"""        eq_{i} = MathTex(r"{safe_tex}", font_size=36)
        eq_{i}.next_to(img, DOWN, buff=0.4)
        self.play(Write(eq_{i}), run_time=1.2)
        self.wait(0.8)
"""
    comment = request.user_prompt.replace('"""', "'")
    src = f'''\
    """Auto-generated by manim-data-viz-bridge. User intent (comment only):
    {comment}
    """
    from manim import *

    config.background_color = "#1C1C1C"

    class {cls}(Scene):
        def construct(self):
            title = Text("{_escape_text(request.viz.title)}", font_size=40, color=BLUE)
            title.to_edge(UP)
            self.play(FadeIn(title, shift=DOWN), run_time=1.2)
            self.wait(0.5)

            img = ImageMobject("{chart_filename}")
            img.scale(0.85)
            img.next_to(title, DOWN, buff=0.35)
            self.play(FadeIn(img, shift=UP), run_time=2.0)
            self.wait(1.0)
    {tex_block}
            self.wait(1.5)
    '''
    return textwrap.dedent(src)


def _escape_text(s: str) -> str:
    """Escape for a normal Python `Text(\"...\")` literal in the emitted file."""
    return s.replace("\\", "\\\\").replace('"', '\\"')
