#!/usr/bin/env bash
set -euo pipefail

# Idempotent setup for the optional Hermes persistent desktop VM.

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info() { printf "%b[info]%b %s\n" "$BLUE" "$NC" "$*"; }
success() { printf "%b[ok]%b %s\n" "$GREEN" "$NC" "$*"; }
warn() { printf "%b[warn]%b %s\n" "$YELLOW" "$NC" "$*"; }
fail() { printf "%b[error]%b %s\n" "$RED" "$NC" "$*" >&2; exit 1; }

on_error() {
  code=$?
  printf "%b[error]%b Setup failed near line %s. Run ./verify.sh for diagnostics, then retry.\n" "$RED" "$NC" "$1" >&2
  exit "$code"
}
trap 'on_error $LINENO' ERR

cd "$(dirname "$0")"

require_cmd() {
  command -v "$1" >/dev/null 2>&1 || fail "$1 is required but was not found. $2"
}

compose() {
  docker compose "$@"
}

random_password() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -base64 24 | tr -d '\n' | tr '/+' 'Aa' | cut -c1-24
  else
    warn "openssl not found; using a less-ideal generated password from /dev/urandom."
    LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 24
  fi
}

write_env() {
  vnc_password=$(random_password)
  hermes_password=$(random_password)
  cat > .env <<EOF
# Generated by hermes-desktop/setup.sh.
# See .env.example for documentation of every variable.
VNC_PASSWORD=${vnc_password}
HERMES_PASSWORD=${hermes_password}
VNC_PORT=5901
NOVNC_PORT=6080
TERMINAL_SSH_PORT=2222
VNC_RESOLUTION=1920x1080
AUTHORIZED_KEYS=
COMPUTER_USE_ENABLED=true
COMPUTER_USE_BACKEND=ssh
COMPUTER_USE_DISPLAY=:1
COMPUTER_USE_VNC_URL=http://localhost:6080/vnc.html
TERMINAL_SSH_HOST=localhost
TERMINAL_SSH_USER=hermes
EOF
  chmod 600 .env
}

check_port_free() {
  port="$1"
  name="$2"
  if command -v ss >/dev/null 2>&1; then
    ss -ltn | awk '{print $4}' | grep -Eq "[:.]${port}$" && warn "Port ${port} (${name}) already appears to be in use. Change it in .env if Docker cannot bind it."
  elif command -v lsof >/dev/null 2>&1; then
    lsof -iTCP:"$port" -sTCP:LISTEN >/dev/null 2>&1 && warn "Port ${port} (${name}) already appears to be in use. Change it in .env if Docker cannot bind it."
  fi
}

info "Hermes Desktop setup starting"

require_cmd docker "Install Docker: https://docs.docker.com/get-docker/"
require_cmd curl "Install curl or use your package manager to add it."

docker compose version >/dev/null 2>&1 || fail "Docker Compose v2 is required. Install the Docker Compose plugin."
docker info >/dev/null 2>&1 || fail "Docker is installed but not running. Start Docker, then run this script again."

if [ ! -f .env ]; then
  info "Creating .env with generated passwords"
  write_env
  success "Created .env with secure generated VNC and SSH passwords"
else
  success ".env already exists; leaving it unchanged"
fi

# Safe to create repeatedly. Useful if users later switch named volumes to bind mounts.
mkdir -p profile screenshots logs sessions
success "Ensured local runtime directories exist: profile screenshots logs sessions"

# shellcheck disable=SC1091
. ./.env
check_port_free "${NOVNC_PORT:-6080}" "noVNC"
check_port_free "${VNC_PORT:-5901}" "VNC"
check_port_free "${TERMINAL_SSH_PORT:-2222}" "SSH"

info "Building desktop image"
compose build desktop

info "Starting desktop container"
compose up -d desktop

info "Preparing persistent browser profile inside container"
docker exec hermes-desktop sh -lc 'mkdir -p /home/hermes/.config/google-chrome && chown -R hermes:hermes /home/hermes/.config' >/dev/null

info "Waiting for services to become healthy"
healthy=0
for i in $(seq 1 60); do
  if ./verify.sh --quiet; then
    healthy=1
    success "Hermes Desktop is running"
    break
  fi
  sleep 2
  printf "."
done
printf "\n"

if [ "$healthy" -ne 1 ]; then
  ./verify.sh || true
  fail "Desktop did not pass health checks in time. See: docker logs hermes-desktop"
fi

cat <<EOF

${GREEN}Setup complete.${NC}

Open the live desktop:
  http://localhost:${NOVNC_PORT:-6080}/vnc.html

SSH test:
  ssh -p ${TERMINAL_SSH_PORT:-2222} hermes@localhost "echo connected"

Add these to the Hermes process environment (for example ~/.hermes/.env):
  COMPUTER_USE_ENABLED=true
  COMPUTER_USE_BACKEND=ssh
  COMPUTER_USE_DISPLAY=:1
  COMPUTER_USE_VNC_URL=http://localhost:${NOVNC_PORT:-6080}/vnc.html
  TERMINAL_SSH_HOST=localhost
  TERMINAL_SSH_PORT=${TERMINAL_SSH_PORT:-2222}
  TERMINAL_SSH_USER=hermes

Then restart Hermes so tool discovery can register computer_use.
Run ./verify.sh any time to check the desktop stack.
EOF
