"""HermesKernel — persistent Python interpreter for one agent session.

One HermesKernel instance is created per AIAgent session when CodeAct mode is
active.  It owns a long-lived subprocess running codeact_kernel_process.py and
a Unix domain socket for bidirectional IPC.

Execution model
---------------
Parent sends {"type": "exec", "code": "..."}  and then enters a receive loop.
The kernel may send zero or more {"type": "tool_call", ...} messages mid-exec
(one per Hermes tool called from Python).  The parent dispatches each tool
synchronously and sends {"type": "tool_result", ...} back.  When the code block
finishes, the kernel sends {"type": "exec_result", ...} and the parent returns.

This means the parent's ``execute()`` method is blocking but handles
interleaved tool call IPC transparently.
"""

from __future__ import annotations

import json
import logging
import os
import socket
import subprocess
import sys
import tempfile
import threading
from pathlib import Path
from typing import TYPE_CHECKING, Callable, Optional

if TYPE_CHECKING:
    from tools.registry import ToolRegistry

logger = logging.getLogger(__name__)

# Hard limit on stdout returned from a single exec() call.
_MAX_STDOUT_CHARS = 50_000
# Hard limit on stderr.
_MAX_STDERR_CHARS = 10_000


class KernelError(RuntimeError):
    """Raised when the kernel process returns an error or crashes."""


class KernelNotStartedError(KernelError):
    """Raised when execute() is called before start()."""


def _truncate(text: str, limit: int, label: str = "output") -> str:
    if len(text) <= limit:
        return text
    head = int(limit * 0.4)
    tail = limit - head
    omitted = len(text) - limit
    return (
        text[:head]
        + f"\n\n... [{label.upper()} TRUNCATED — {omitted:,} chars omitted] ...\n\n"
        + text[-tail:]
    )


def _tool_result_error_for_kernel(tool_name: str, result: object) -> str:
    """Promote selected tool-level JSON errors into CodeAct exceptions."""
    if tool_name not in {"web_search", "web_extract"}:
        return ""
    try:
        parsed = result if isinstance(result, dict) else json.loads(str(result))
    except Exception:
        return ""
    if not isinstance(parsed, dict):
        return ""
    error = parsed.get("error")
    success = parsed.get("success")
    if not error and success is not False:
        return ""
    detail = str(error or f"{tool_name} returned success=false").strip()
    if tool_name == "web_search":
        return (
            f"web_search failed: {detail}. For research/report/latest/current tasks, "
            "use research_web(...) or research_gather instead of retrying raw "
            "web_search. If the failure is a rate limit, bot block, JS challenge, "
            "Cloudflare/Wikipedia block, try browser/Camofox/Scrapling fallbacks "
            "when available or switch to alternate primary sources."
        )
    return (
        f"web_extract failed: {detail}. For reports/current research, use "
        "research_web(...) or research_gather so Hermes can search, extract, "
        "fallback, and report gaps. If extraction is blocked by bot protection, "
        "JS challenges, Cloudflare/Wikipedia blocks, try browser/Camofox/"
        "Scrapling fallbacks when available."
    )


class HermesKernel:
    """Manages one persistent CodeAct Python subprocess for an agent session.

    Parameters
    ----------
    session_id:
        Owning session identifier (used for the UDS socket path).
    tool_dispatcher:
        Callable ``(tool_name, args) -> str`` that routes tool calls from the
        kernel back to the Hermes registry.  Typically wraps
        ``handle_function_call`` from ``model_tools``.
    namespace_source:
        Python source string that defines tool stubs + help().  Generated by
        ``agent.codeact_namespace.build_tool_namespace_source()``.
    """

    def __init__(
        self,
        session_id: str,
        tool_dispatcher: Callable[[str, dict], str],
        namespace_source: str,
    ) -> None:
        self._session_id = session_id
        self._tool_dispatcher = tool_dispatcher
        self._namespace_source = namespace_source

        self._proc: Optional[subprocess.Popen] = None
        self._server_sock: Optional[socket.socket] = None
        self._conn: Optional[socket.socket] = None
        self._conn_file = None
        self._sock_path: Optional[str] = None
        self._lock = threading.Lock()  # serialise concurrent execute() calls
        self._started = False

    # ------------------------------------------------------------------
    # Lifecycle
    # ------------------------------------------------------------------

    def start(self) -> None:
        """Spawn the kernel subprocess and complete the init handshake."""
        if self._started:
            return

        # Create a temp UDS socket path.
        tmp = tempfile.mktemp(prefix="hermes_codeact_", suffix=".sock")
        self._sock_path = tmp

        # Listen before spawning so the child can connect immediately.
        self._server_sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
        self._server_sock.bind(tmp)
        self._server_sock.listen(1)

        # Scrub credential env vars (mirrors execute_code sandboxing).
        env = _scrub_env(os.environ.copy())
        env["HERMES_CODEACT_SOCKET"] = tmp

        kernel_script = str(
            Path(__file__).resolve().parent / "codeact_kernel_process.py"
        )
        self._proc = subprocess.Popen(
            [sys.executable, kernel_script],
            env=env,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.PIPE,
        )

        # Accept the single kernel connection (timeout = 10 s).
        self._server_sock.settimeout(10.0)
        try:
            self._conn, _ = self._server_sock.accept()
        except socket.timeout:
            self._proc.kill()
            raise KernelError("Kernel subprocess did not connect within 10 s")
        finally:
            self._server_sock.settimeout(None)

        self._conn_file = self._conn.makefile("rb")

        # Send init message with namespace source.
        self._send({"type": "init", "namespace_source": self._namespace_source})
        response = self._recv()
        if response.get("type") != "ready":
            tb = response.get("traceback", "unknown error")
            raise KernelError(f"Kernel init failed:\n{tb}")

        self._started = True
        logger.debug("CodeAct kernel started (session=%s, socket=%s)", self._session_id, tmp)

    def execute(self, code: str) -> str:
        """Execute *code* in the persistent kernel and return a result string.

        Blocks until execution completes (including any interleaved tool calls).
        Returns a human-readable string with stdout, last value, and/or errors.
        """
        if not self._started:
            raise KernelNotStartedError("Call start() before execute()")

        with self._lock:
            return self._execute_locked(code)

    def _execute_locked(self, code: str) -> str:
        self._send({"type": "exec", "code": code})

        while True:
            msg = self._recv()
            msg_type = msg.get("type", "")

            if msg_type == "tool_call":
                # Kernel is requesting a Hermes tool call — dispatch and reply.
                tool_name = msg.get("tool", "")
                args = msg.get("args", {})
                try:
                    result = self._tool_dispatcher(tool_name, args)
                except Exception as exc:
                    result = json.dumps({"error": str(exc)})
                    self._send({"type": "tool_result", "result": result,
                                "error": str(exc)})
                    continue
                tool_error = _tool_result_error_for_kernel(tool_name, result)
                if tool_error:
                    self._send({
                        "type": "tool_result",
                        "result": result,
                        "error": tool_error,
                    })
                else:
                    self._send({"type": "tool_result", "result": result})

            elif msg_type == "exec_result":
                return _format_exec_result(msg)

            elif msg_type == "error":
                raise KernelError(msg.get("traceback") or msg.get("error", "unknown kernel error"))

            else:
                logger.warning("Unexpected kernel message type: %r", msg_type)

    def soft_reset(self) -> int:
        """Clear user-defined variables from the kernel namespace.

        Returns the number of names removed.
        Protected entries (tool stubs, help, __protected__) are preserved.
        """
        if not self._started:
            return 0
        with self._lock:
            self._send({"type": "soft_reset"})
            response = self._recv()
            return response.get("removed", 0)

    def hard_reset(self) -> None:
        """Kill the kernel subprocess and spawn a fresh one."""
        self.shutdown(quiet=True)
        self._started = False
        self.start()

    def shutdown(self, quiet: bool = False) -> None:
        """Gracefully shut down the kernel subprocess."""
        if not self._started:
            return
        try:
            with self._lock:
                self._send({"type": "quit"})
                self._recv()  # "bye"
        except Exception:
            pass
        finally:
            self._cleanup()
        if not quiet:
            logger.debug("CodeAct kernel shut down (session=%s)", self._session_id)

    def _cleanup(self) -> None:
        for obj in (self._conn_file, self._conn, self._server_sock):
            if obj is not None:
                try:
                    obj.close()
                except Exception:
                    pass
        if self._proc is not None:
            try:
                self._proc.kill()
                self._proc.wait(timeout=5)
            except Exception:
                pass
        if self._sock_path and os.path.exists(self._sock_path):
            try:
                os.unlink(self._sock_path)
            except OSError:
                pass
        self._proc = None
        self._conn = None
        self._conn_file = None
        self._server_sock = None
        self._sock_path = None
        self._started = False

    def __del__(self) -> None:
        try:
            self.shutdown(quiet=True)
        except Exception:
            pass

    # ------------------------------------------------------------------
    # Internal I/O
    # ------------------------------------------------------------------

    def _send(self, msg: dict) -> None:
        data = (json.dumps(msg, ensure_ascii=False) + "\n").encode()
        self._conn.sendall(data)

    def _recv(self) -> dict:
        line = self._conn_file.readline()
        if not line:
            raise KernelError("Kernel process disconnected unexpectedly")
        return json.loads(line.strip())

    # ------------------------------------------------------------------
    # Properties
    # ------------------------------------------------------------------

    @property
    def is_started(self) -> bool:
        return self._started

    @property
    def session_id(self) -> str:
        return self._session_id


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

_CRED_PATTERNS = frozenset({
    "KEY", "TOKEN", "SECRET", "PASSWORD", "CREDENTIAL", "PASSWD", "AUTH",
})

_SAFE_PREFIXES = frozenset({
    "PATH", "HOME", "USER", "LANG", "LC_", "TERM", "TMP", "TEMP", "SHELL",
    "LOGNAME", "XDG_", "PYTHONPATH", "VIRTUAL_ENV", "CONDA_", "HERMES_",
    "HERMES_CODEACT_SOCKET",
})


def _scrub_env(env: dict[str, str]) -> dict[str, str]:
    """Remove credential env vars from the subprocess environment."""
    scrubbed = {}
    for key, value in env.items():
        key_upper = key.upper()
        if any(pat in key_upper for pat in _CRED_PATTERNS):
            continue
        scrubbed[key] = value
    return scrubbed


def _format_exec_result(msg: dict) -> str:
    """Build a human-readable result string from an exec_result message."""
    parts: list[str] = []

    stdout = _truncate(msg.get("stdout", ""), _MAX_STDOUT_CHARS, "stdout")
    stderr = _truncate(msg.get("stderr", ""), _MAX_STDERR_CHARS, "stderr")
    last_value = msg.get("last_value")
    tb = msg.get("traceback", "")

    if stdout.strip():
        parts.append(stdout.rstrip())
    if last_value is not None and last_value.strip():
        parts.append(f"=> {last_value}")
    if stderr.strip():
        parts.append(f"[stderr]\n{stderr.rstrip()}")
    if tb:
        parts.append(f"[error]\n{tb.rstrip()}")

    return "\n".join(parts) if parts else "(no output)"
